### ISSUE TITLE
can you please help me on this

### ISSUE THREAD

**Issue by modyamash** [gabedunn-archive/devmod-v5#56]
```
PS E:\BOTS\devmod-master> node ./src/esm.js
E:\BOTS\devmod-master\src\utils\config.js:1
TypeError: Cannot read property 'channels' of undefined
    at Object.<anonymous> (E:\BOTS\devmod-master\src\utils\config.js:20:19)  
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
PS E:\BOTS\devmod-master> 
```

**Comment by redxtech** [comment]
Have you made a channels entry in the config?

Or have you made a config? This means that you haven't specified your own config and since you haven't done that, you can't access the channels thing. I can fix this in a future patch, so I'll keep the issue open, but to fix it for now you can create your own config & add some channels to it.

**Comment by redxtech** [comment]
Since there haven't been any updates I'm going to close this.
